name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ubuntu-latest Node ${{ matrix.node }} Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: npm run build
